### ISSUE TITLE
example does not run

### ISSUE THREAD

**Issue by tve** [tdunning/anomaly-detection#2]
I'm trying to run the example on Ubuntu 16.04 x64 and I get:
```
> mvn -q exec:java -e -Dexec.mainClass=com.tdunning.sparse.Learn
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project AnomalyDetector: An exception occured while executing the Java class. com.tdunning.sparse.Learn -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project AnomalyDetector: An exception occured while executing the Java class. com.tdunning.sparse.Learn
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
```
I have openjdk-9 installed. Any hints? (I'm not a Java user...)

**Comment by tve** [comment]
Looks like it's class search path issue:
```
[DEBUG] joining on thread Thread[com.tdunning.sparse.Learn.main(),5,com.tdunning.sparse.Learn]
[WARNING]
java.lang.ClassNotFoundException: com.tdunning.sparse.Learn
        at java.net.URLClassLoader.findClass(java.base@9-internal/URLClassLoader.java:384)
```

**Comment by tve** [comment]
Trying to unravel all this maven stuff (yes, I'm not a Java programmer):
```
> mvn install exec:java
[...]
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project AnomalyDetector: The parameters 'mainClass' for goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java are missing or invalid -> [Help 1]
```

**Comment by tdunning** [comment]
Yeah. That is odd.  Let me get back to my computer and take a look. At
dinner now.

The Java 9 thought is possible. It could be Maven versioning or something
else as well like install issues in your environment. Or I could have
screwed up.

Hard to say until I look.
